### ISSUE TITLE
It get stuck when verbose shows:  IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0

### ISSUE THREAD

**Issue by fhob** [myspaghetti/macos-guest-virtualbox#199]
Hi, myspaghetti

The script is not working for me, on boot install get stuck when on 
IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0

Fabien

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report. If you wouldn't mind please run the following command and attach the resulting `troubleshoot.txt` file here:
```
./macos-guest-virtualbox.sh troubleshoot > troubleshoot.txt
```
The output includes system information, VirtualBox logs, and checksums for some installation files, and might contain path names from your device.

**Comment by myspaghetti** [comment]
I'm assuming this was resolved, possibly by assigning a CPU profile? Closing.

**Comment by fhob** [comment]
Nope, this problem happens for Catalina

Here is corresponding troubleshoot.txt

[troubleshoot.txt](https://github.com/myspaghetti/macos-guest-virtualbox/files/4582226/troubleshoot.txt)

**Comment by myspaghetti** [comment]
Looks like the Catalina `InstallESDDmg.pkg` version `10.15.4.0.0.1587988616` file is damaged. The md5sum for the file is `33d092c905aaba0c8512f150d853609d`

The rest of the files' checksums are correct.

Delete `Catalina_InstallESDDmg.pkg` and all the `.part` files and run the script again.

**Comment by fhob** [comment]
Hello,

I retrieved Catalina_InstallESDDmg again.
The MD5 is now correct, but the initial problem persists 


[troubleshoot.txt](https://github.com/myspaghetti/macos-guest-virtualbox/files/4586697/troubleshoot.txt)

**Comment by myspaghetti** [comment]
The log says VT-x is not available on your machine:
```
00:00:03.365864 HM: HMR3Init: Attempting fall back to NEM: VT-x is not available
```
Make sure Hyper-V and other Windows virtualization services (Windows Sandbox, WSL2, and so on) are not installed, and that core isolation memory integrity is disabled.

**Comment by fhob** [comment]
Disabled  Hyper-V  and worked! 
Thank you :=)
Maybe the script should check this in the prerequisite

**Comment by fhob** [comment]
Disabled  Hyper-V  and worked! 
Thank you :=)
Maybe the script should check this in the prerequisite
